version: 2
jobs:
   michael:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "A first hello"
   jordan:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "Double the trouble!"
workflows:
  version: 2
  michael_jordan:
    jobs:
      - jordan
      - michael
